### PR TITLE
Update Typescript Version

### PR DESCRIPTION
**Pull request by dermasmid**

### CODE REVIEW

**Comment by dermasmid** [comment]
pls note, i did not get the tests to work yet, ill try to get back to it

**Comment by lhoste-bell** [comment]
Hi Cheskel, thanks for your contribution!

If you downgrade to chai@4, you can run the tests using node 20, see https://github.com/chaijs/chai/issues/1561 for more information. 

With this version of chai, serialize-closures passes, but I do get the following exception for ts-closure-transform.
I'll keep this PR open for now.
```
TSError: ⨯ Unable to compile TypeScript:
compile.ts:59:77 - error TS2345: Argument of type '{ before: Transform[]; after: Transform[]; }' is not assignable to parameter of type 'CustomTransformers'.
  Types of property 'before' are incompatible.
    Type 'Transform[]' is not assignable to type '(TransformerFactory<SourceFile> | CustomTransformerFactory)[]'.
      Type 'Transform' is not assignable to type 'TransformerFactory<SourceFile> | CustomTransformerFactory'.
        Type 'Transform' is not assignable to type 'TransformerFactory<SourceFile>'.
          Type 'Transformer<Node>' is not assignable to type 'Transformer<SourceFile>'.
            Type 'Node' is missing the following properties from type 'SourceFile': statements, endOfFileToken, fileName, text, and 15 more.

59   let emitResult = program.emit(undefined, writeFile, undefined, undefined, transformers);
```

**Comment by dermasmid** [comment]
thanks for the input, i plan to come back to this to get the tests to pass, for now i got my thing to work with the current changes

**Comment by dermasmid** [comment]
tests are passing, for some reason i had to do this https://github.com/nokia/ts-serialize-closures/pull/16/commits/861e09e1823ba331f7067a5df08c6a7567e43ded

the order for them changed

**Comment by lhoste-bell** [comment]
Looks great! The last commit however, we should not apply because the logic is flawed.
For some reason, the hoisting of the tct_transform variable does not happen correctly. https://github.com/nokia/ts-serialize-closures/blob/5c70c2679fc86e11955b9776ed11653b5d09c9bf/ts-closure-transform/src/transform.ts#L215

**Comment by dermasmid** [comment]
ok, thanks, ill try to see where it broke, unless you can do it

**Comment by dermasmid** [comment]
trying to understand what `hoistVariableDeclaration` should be doing, since its a var its not a problem that its at the bottom, right?

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

**Comment by lhoste-bell** [comment]
The following snippet puts the var declaration at the top, but you're right it doesn't matter. Thanks for looking into this.
 
```
import * as ts from "typescript";
const code = `
function createCounter() {
  let count = 0;
  return {
    get: (() => count),
    increment: (() => { count++; })
  };
}`;

const out = ts.transpileModule(code, {
  compilerOptions: { target: ts.ScriptTarget.ES5 },
  transformers: { before: [transfromer()] },
});
console.log(out.outputText);

function transfromer() {
  return (ctx: ts.TransformationContext) => {
    return (sourceFile: ts.SourceFile) => {
      function visitor(node: ts.Node): ts.Node {
        const parent = node.parent;
        if (ts.isFunctionDeclaration(node)) {
          let visited = ts.visitEachChild(node.body, visitor, ctx);
          let visitedFunc = ts.factory.updateFunctionDeclaration(
            node,
            node.modifiers,
            node.asteriskToken,
            node.name,
            node.typeParameters,
            node.parameters,
            node.type,
            visited
          );

          return visitedFunc;
        } else if (ts.isArrowFunction(node) || ts.isFunctionExpression(node)) {
          let temp = ts.factory.createUniqueName("_tct_transform");
          ctx.hoistVariableDeclaration(temp);
          return ts.factory.createCommaListExpression([
            ts.factory.createAssignment(temp, node),
            temp,
          ]);
        }
        return ts.visitEachChild(node, visitor, ctx);
      }
      return ts.visitEachChild(sourceFile, visitor, ctx);
    };
  };
}
```

**Comment by lhoste-bell** [comment]
Merged https://github.com/nokia/ts-serialize-closures/compare/270b89b7e9312c2c898a70e90f1e3900fa2ece9c...f8a337db6ea75ea468595907a2eaf3bb9ca69548 👍

**Comment by dermasmid** [comment]
pls lmk when you published it to npm, thanks for the fast response times

**Comment by lhoste-bell** [comment]
Will do, going to test our internal packages and if they succeed I'll make a new release.

**Comment by lhoste-bell** [comment]
Released
ts-closure-transform@0.2.0
serialize-closures@0.3.0

**Comment by dermasmid** [comment]
thank you!

**Comment by lhoste-bell** [comment]
Many thanks to you too!

**Pull request closed without merging**
